// Code generated by MockGen. DO NOT EDIT.
// Source: handlers/handlers.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/junpayment/oshiete/models"
	iruka "github.com/junpayment/oshiete/models/iruka"
	reflect "reflect"
)

// MockTemplateService is a mock of TemplateService interface
type MockTemplateService struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateServiceMockRecorder
}

// MockTemplateServiceMockRecorder is the mock recorder for MockTemplateService
type MockTemplateServiceMockRecorder struct {
	mock *MockTemplateService
}

// NewMockTemplateService creates a new mock instance
func NewMockTemplateService(ctrl *gomock.Controller) *MockTemplateService {
	mock := &MockTemplateService{ctrl: ctrl}
	mock.recorder = &MockTemplateServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTemplateService) EXPECT() *MockTemplateServiceMockRecorder {
	return m.recorder
}

// OutEte mocks base method
func (m *MockTemplateService) OutEte(answer *models.EteAnswer) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutEte", answer)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutEte indicates an expected call of OutEte
func (mr *MockTemplateServiceMockRecorder) OutEte(answer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutEte", reflect.TypeOf((*MockTemplateService)(nil).OutEte), answer)
}

// OutIruka mocks base method
func (m *MockTemplateService) OutIruka(states []*iruka.State) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutIruka", states)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutIruka indicates an expected call of OutIruka
func (mr *MockTemplateServiceMockRecorder) OutIruka(states interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutIruka", reflect.TypeOf((*MockTemplateService)(nil).OutIruka), states)
}
