// Code generated by MockGen. DO NOT EDIT.
// Source: handlers/iruka.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	iruka "github.com/junpayment/oshiete/models/iruka"
	reflect "reflect"
)

// MockIrukaService is a mock of IrukaService interface
type MockIrukaService struct {
	ctrl     *gomock.Controller
	recorder *MockIrukaServiceMockRecorder
}

// MockIrukaServiceMockRecorder is the mock recorder for MockIrukaService
type MockIrukaServiceMockRecorder struct {
	mock *MockIrukaService
}

// NewMockIrukaService creates a new mock instance
func NewMockIrukaService(ctrl *gomock.Controller) *MockIrukaService {
	mock := &MockIrukaService{ctrl: ctrl}
	mock.recorder = &MockIrukaServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIrukaService) EXPECT() *MockIrukaServiceMockRecorder {
	return m.recorder
}

// GetList mocks base method
func (m *MockIrukaService) GetList() ([]*iruka.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList")
	ret0, _ := ret[0].([]*iruka.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList
func (mr *MockIrukaServiceMockRecorder) GetList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockIrukaService)(nil).GetList))
}
