// Code generated by MockGen. DO NOT EDIT.
// Source: services/iruka.go

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	iruca "github.com/junpayment/oshiete/models/iruca"
	reflect "reflect"
)

// MockIrucaClient is a mock of IrucaClient interface
type MockIrucaClient struct {
	ctrl     *gomock.Controller
	recorder *MockIrucaClientMockRecorder
}

// MockIrucaClientMockRecorder is the mock recorder for MockIrucaClient
type MockIrucaClientMockRecorder struct {
	mock *MockIrucaClient
}

// NewMockIrucaClient creates a new mock instance
func NewMockIrucaClient(ctrl *gomock.Controller) *MockIrucaClient {
	mock := &MockIrucaClient{ctrl: ctrl}
	mock.recorder = &MockIrucaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIrucaClient) EXPECT() *MockIrucaClientMockRecorder {
	return m.recorder
}

// GetMembers mocks base method
func (m *MockIrucaClient) GetMembers() ([]*iruca.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMembers")
	ret0, _ := ret[0].([]*iruca.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMembers indicates an expected call of GetMembers
func (mr *MockIrucaClientMockRecorder) GetMembers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMembers", reflect.TypeOf((*MockIrucaClient)(nil).GetMembers))
}
